version: "3.9"

services:
  php-fpm:
    build:
      context: .
    container_name: php-fpm
    volumes:
      - ../:/var/www/html:cached
    user: "${UID}:${GID}"
    environment:
      TZ: UTC
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    depends_on:
      - php-fpm
    volumes:
      - ../:/var/www/html:cached
      - ./nginx/sites:/etc/nginx/sites
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"       # web
      - "5173:5173"   # Vite
      - "6001:6001"   # Laravel Echo Server
    restart: unless-stopped

  composer:
    image: composer:latest
    container_name: composer
    working_dir: /var/www/html
    volumes:
      - ../:/var/www/html:cached
    entrypoint: ["composer"]
    restart: "no"

  node:
    image: node:18
    container_name: node
    working_dir: /projects
    volumes:
      - ../:/projects
    command: tail -f /dev/null
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravelpass
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: unless-stopped

volumes:
  mysql_data:
